spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: grass
    password: 230407
  flyway:
    baseline-on-migrate: true





server:
  port: 8084

  spring:
    main:
      allow-bean-definition-overriding: true


